# Generated by `tuvl codegen` from the project's workflows. Do not edit:
# changes are overwritten. tuvl-generated
# ruff: noqa
# fmt: off

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Review(BaseModel):
    """Model Review (read)."""

    model_config = ConfigDict(extra="ignore")

    id: UUID | None = None
    text: str
    source: str | None = None
    sentiment: Literal["positive", "neutral", "negative"]
    confidence: float
    created_at: datetime | None = None


class AnalyzeSentimentInput(BaseModel):
    """Trigger input of workflow 'analyze_sentiment'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    text: str
    source: str | None = None


class ClassifyIn(BaseModel):
    """Inputs of 'classify' (analyze_sentiment)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    text: str


class ClassifyOut(BaseModel):
    """Outputs of 'classify' (analyze_sentiment)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    sentiment: Literal["positive", "neutral", "negative"]
    confidence: float


class PersistIn(BaseModel):
    """Inputs of 'persist' (analyze_sentiment)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    text: str
    source: str | None = None
    sentiment: Literal["positive", "neutral", "negative"]
    confidence: float


class PersistOut(BaseModel):
    """Outputs of 'persist' (analyze_sentiment)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    review: Review


AnalyzeSentimentEnd = Literal["default", "failed"]
