# Generated by `tuvl codegen` from the project's workflows. Do not edit:
# changes are overwritten. tuvl-generated
# ruff: noqa
# fmt: off

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, JsonValue


class AccountCredit(BaseModel):
    """Model AccountCredit (read)."""

    model_config = ConfigDict(extra="ignore")

    id: UUID | None = None
    customer_id: str
    amount: float
    reason: str | None = None
    created_at: datetime | None = None


class SupportTicket(BaseModel):
    """Model SupportTicket (read)."""

    model_config = ConfigDict(extra="ignore")

    id: UUID | None = None
    subject: str | None = None
    body: str | None = None
    category: str | None = None
    urgency: str | None = None
    resolution: str | None = None
    created_at: datetime | None = None


class IssueCreditInput(BaseModel):
    """Trigger input of workflow 'issue_credit'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    customer_id: str
    amount: int
    reason: str


class CreditIn(BaseModel):
    """Inputs of 'credit' (issue_credit)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    customer_id: str
    amount: int
    reason: str


class CreditOut(BaseModel):
    """Outputs of 'credit' (issue_credit)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    credit: AccountCredit


class TriageInput(BaseModel):
    """Trigger input of workflow 'triage'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    customer_id: str
    subject: str
    body: str


class ClassifyIn(BaseModel):
    """Inputs of 'classify' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    subject: str
    body: str


class ClassifyOut(BaseModel):
    """Outputs of 'classify' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    category: Literal["billing", "technical", "account"]
    urgency: Literal["low", "medium", "high"]


class RouteIn(BaseModel):
    """Inputs of 'route' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    category: Literal["billing", "technical", "account"]
    urgency: Literal["low", "medium", "high"]
    subject: str
    body: str


class RouteOut(BaseModel):
    """Outputs of 'route' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    route: Literal["investigate", "store"]


class InvestigateIn(BaseModel):
    """Inputs of 'investigate' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    customer_id: str
    subject: str
    body: str


class InvestigateOut(BaseModel):
    """Outputs of 'investigate' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    resolution: str


class LookupAccountIn(BaseModel):
    """Inputs of 'lookup_account' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    customer_id: str


class LookupAccountOut(BaseModel):
    """Outputs of 'lookup_account' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    account: JsonValue


class PersistIn(BaseModel):
    """Inputs of 'persist' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    subject: str
    body: str
    category: Literal["billing", "technical", "account"]
    urgency: Literal["low", "medium", "high"]
    resolution: str | None = None


class PersistOut(BaseModel):
    """Outputs of 'persist' (triage)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    ticket: SupportTicket


IssueCreditEnd = Literal["default", "failed"]
TriageEnd = Literal["default", "failed"]
RouteSignal = Literal["investigate", "store"]
InvestigateSignal = Literal["resolved", "needs_human"]
