# Generated by `tuvl codegen` from the project's workflows. Do not edit:
# changes are overwritten. tuvl-generated
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class ModerateContentInput(BaseModel):
    """Trigger input of workflow 'moderate_content'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    author_id: str
    region: Literal["us", "eu", "in"]
    content: str


class ClassifyIn(BaseModel):
    """Inputs of 'classify' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    region: Literal["us", "eu", "in"]
    content: str


class ClassifyOut(BaseModel):
    """Outputs of 'classify' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    verdict: Literal["safe", "borderline", "violation"]
    rationale: str
    confidence: float


class ApplyPolicyIn(BaseModel):
    """Inputs of 'apply_policy' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    region: Literal["us", "eu", "in"]
    verdict: Literal["safe", "borderline", "violation"]
    rationale: str


class ApplyPolicyOut(BaseModel):
    """Outputs of 'apply_policy' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    category: Literal["safe", "borderline", "violation"]
    reason: str


class ReviewIn(BaseModel):
    """Inputs of 'review' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    author_id: str
    region: Literal["us", "eu", "in"]
    content: str


class ReviewOut(BaseModel):
    """Outputs of 'review' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    decision: Literal["approve", "remove"]
    note: str | None = None


class RecordIn(BaseModel):
    """Inputs of 'record' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    author_id: str
    region: Literal["us", "eu", "in"]
    content: str
    category: Literal["safe", "borderline", "violation"] | None = None
    reason: str | None = None
    decision: Literal["approve", "remove"] | None = None
    note: str | None = None


class RecordOut(BaseModel):
    """Outputs of 'record' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    item_id: UUID
    status: Literal["approved", "removed"]
    recorded_category: Literal["safe", "borderline", "violation"]
    action: str


class NotifyIn(BaseModel):
    """Inputs of 'notify' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    author_id: str
    region: Literal["us", "eu", "in"]
    recorded_category: Literal["safe", "borderline", "violation"]
    reason: str | None = None
    item_id: UUID


class NotifyOut(BaseModel):
    """Outputs of 'notify' (moderate_content)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)


ModerateContentEnd = Literal["default", "failed"]
ApplyPolicySignal = Literal["safe", "violation", "borderline"]
ReviewSignal = Literal["approve", "remove"]
RecordSignal = Literal["notify", "recorded"]
