# Generated by `tuvl codegen` from the project's workflows. Do not edit:
# changes are overwritten. tuvl-generated
# ruff: noqa
# fmt: off

from __future__ import annotations

from datetime import date, datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, JsonValue


class Applicant(BaseModel):
    """Model Applicant (read)."""

    model_config = ConfigDict(extra="ignore")

    id: UUID | None = None
    full_name: str
    dob: date | None = None
    national_id: str
    email: str
    country: Literal["us", "gb", "de", "in", "sg"]
    status: Literal["received", "investigating", "pending_review", "approved", "rejected"] | None = None
    created_at: datetime | None = None


class IngestPolicyInput(BaseModel):
    """Trigger input of workflow 'ingest_policy'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    title: str
    content: str


class IngestIn(BaseModel):
    """Inputs of 'ingest' (ingest_policy)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    title: str
    content: str


class IngestOut(BaseModel):
    """Outputs of 'ingest' (ingest_policy)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    doc_id: UUID


class OnboardApplicantInput(BaseModel):
    """Trigger input of workflow 'onboard_applicant'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    full_name: str
    dob: date
    national_id: str
    email: str
    country: Literal["us", "gb", "de", "in", "sg"]


class PersistApplicantIn(BaseModel):
    """Inputs of 'persist_applicant' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    full_name: str
    dob: date
    national_id: str
    email: str
    country: Literal["us", "gb", "de", "in", "sg"]


class PersistApplicantOut(BaseModel):
    """Outputs of 'persist_applicant' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    applicant: Applicant


class ApplicantRefIn(BaseModel):
    """Inputs of 'applicant_ref' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    applicant: Applicant


class ApplicantRefOut(BaseModel):
    """Outputs of 'applicant_ref' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    applicant_id: UUID


class SanctionsScreenIn(BaseModel):
    """Inputs of 'sanctions_screen' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    full_name: str
    dob: date
    country: Literal["us", "gb", "de", "in", "sg"]


class SanctionsScreenOut(BaseModel):
    """Outputs of 'sanctions_screen' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    screened_country: str


class PolicyContextIn(BaseModel):
    """Inputs of 'policy_context' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    country: Literal["us", "gb", "de", "in", "sg"]


class PolicyContextOut(BaseModel):
    """Outputs of 'policy_context' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    policies: list[JsonValue]


class InvestigateIn(BaseModel):
    """Inputs of 'investigate' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    applicant_id: UUID
    country: Literal["us", "gb", "de", "in", "sg"]
    policies: list[JsonValue]


class InvestigateOut(BaseModel):
    """Outputs of 'investigate' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    investigation: str


class CheckWatchlistIn(BaseModel):
    """Inputs of 'check_watchlist' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    applicant_id: UUID


class CheckWatchlistOut(BaseModel):
    """Outputs of 'check_watchlist' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    hit: bool
    checked: bool
    source: str | None = None


class AssessIn(BaseModel):
    """Inputs of 'assess' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    investigation: str
    policies: list[JsonValue]


class AssessOut(BaseModel):
    """Outputs of 'assess' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    score: int
    rationale: str


class ReviewIn(BaseModel):
    """Inputs of 'review' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    applicant: Applicant
    investigation: str | None = None
    score: int | None = None
    rationale: str | None = None


class ReviewOut(BaseModel):
    """Outputs of 'review' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    decision: Literal["approve", "reject"]
    band: Literal["low", "medium", "high"]
    note: str | None = None


class FinalizeIn(BaseModel):
    """Inputs of 'finalize' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    applicant: Applicant
    score: int | None = None
    rationale: str | None = None
    decision: Literal["approve", "reject"] | None = None
    band: Literal["low", "medium", "high"] | None = None
    note: str | None = None


class FinalizeOut(BaseModel):
    """Outputs of 'finalize' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    status: Literal["approved", "rejected"]
    final_band: Literal["low", "medium", "high"]


class DiscardApplicantIn(BaseModel):
    """Inputs of 'discard_applicant' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    applicant: Applicant


class DiscardApplicantOut(BaseModel):
    """Outputs of 'discard_applicant' (onboard_applicant)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)


IngestPolicyEnd = Literal["default", "failed"]
OnboardApplicantEnd = Literal["default", "duplicate", "failed"]
InvestigateSignal = Literal["clear", "elevated", "refer_human"]
AssessSignal = Literal["low", "medium", "high"]
ReviewSignal = Literal["approve", "reject"]
