# Generated by `tuvl codegen` from the project's workflows. Do not edit:
# changes are overwritten. tuvl-generated
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, JsonValue


class AskKbInput(BaseModel):
    """Trigger input of workflow 'ask_kb'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    question: str


class SearchIn(BaseModel):
    """Inputs of 'search' (ask_kb)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    question: str


class SearchOut(BaseModel):
    """Outputs of 'search' (ask_kb)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    passages: list[JsonValue]


class AnswerIn(BaseModel):
    """Inputs of 'answer' (ask_kb)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    question: str
    passages: list[JsonValue]


class AnswerOut(BaseModel):
    """Outputs of 'answer' (ask_kb)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    answer: str
    sources: list[str]
    confident: bool


class IngestDocInput(BaseModel):
    """Trigger input of workflow 'ingest_doc'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    title: str
    content: str
    tags: list[str] | None = None


class IngestIn(BaseModel):
    """Inputs of 'ingest' (ingest_doc)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    title: str
    content: str
    tags: list[str] | None = None


class IngestOut(BaseModel):
    """Outputs of 'ingest' (ingest_doc)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    doc_id: UUID


AskKbEnd = Literal["default", "failed"]
IngestDocEnd = Literal["default", "failed"]
