# Generated by `tuvl codegen` from the project's workflows. Do not edit:
# changes are overwritten. tuvl-generated
# ruff: noqa
# fmt: off

from __future__ import annotations

from datetime import date, datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, JsonValue


class InvoiceCreate(BaseModel):
    """Model Invoice (create)."""

    model_config = ConfigDict(extra="ignore")

    vendor_name: str
    invoice_number: str
    invoice_date: date | None = None
    currency: Literal["USD", "EUR", "GBP", "INR"]
    subtotal: float
    tax: float
    total: float
    vendor_tax_id: str | None = None
    status: Literal["extracted", "rejected"]
    raw_text: str | None = None


class Invoice(BaseModel):
    """Model Invoice (read)."""

    model_config = ConfigDict(extra="ignore")

    id: UUID | None = None
    vendor_name: str
    invoice_number: str
    invoice_date: date | None = None
    currency: Literal["USD", "EUR", "GBP", "INR"]
    subtotal: float
    tax: float
    total: float
    vendor_tax_id: str | None = None
    status: Literal["extracted", "rejected"]
    raw_text: str | None = None
    created_at: datetime | None = None


class ExtractInvoiceInput(BaseModel):
    """Trigger input of workflow 'extract_invoice'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    raw_text: str


class ExtractIn(BaseModel):
    """Inputs of 'extract' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    raw_text: str


class ExtractOut(BaseModel):
    """Outputs of 'extract' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    vendor_name: str | None = None
    invoice_number: str | None = None
    invoice_date: date | None = None
    currency: Literal["USD", "EUR", "GBP", "INR"] | None = None
    subtotal: float | None = None
    tax: float | None = None
    total: float | None = None
    vendor_tax_id: str | None = None


class VerifyTotalsIn(BaseModel):
    """Inputs of 'verify_totals' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    vendor_name: str | None = None
    invoice_number: str | None = None
    invoice_date: date | None = None
    currency: Literal["USD", "EUR", "GBP", "INR"] | None = None
    subtotal: float | None = None
    tax: float | None = None
    total: float | None = None
    vendor_tax_id: str | None = None
    raw_text: str


class VerifyTotalsValidOut(BaseModel):
    """Outputs of 'verify_totals' when it emits 'valid' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    invoice: InvoiceCreate
    verification: JsonValue


class VerifyTotalsMismatchOut(BaseModel):
    """Outputs of 'verify_totals' when it emits 'mismatch' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    invoice: InvoiceCreate
    verification: JsonValue


class VerifyTotalsIncompleteOut(BaseModel):
    """Outputs of 'verify_totals' when it emits 'incomplete' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    verification: JsonValue


class PersistIn(BaseModel):
    """Inputs of 'persist' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    invoice: InvoiceCreate


class PersistOut(BaseModel):
    """Outputs of 'persist' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    saved: Invoice


class PersistRejectedIn(BaseModel):
    """Inputs of 'persist_rejected' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    invoice: InvoiceCreate


class PersistRejectedOut(BaseModel):
    """Outputs of 'persist_rejected' (extract_invoice)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    rejected: Invoice


ExtractInvoiceEnd = Literal["default", "duplicate", "failed", "rejected"]
VerifyTotalsResult = tuple[VerifyTotalsValidOut, Literal["valid"]] | tuple[VerifyTotalsMismatchOut, Literal["mismatch"]] | tuple[VerifyTotalsIncompleteOut, Literal["incomplete"]]
