# Generated by `tuvl codegen` from the project's workflows. Do not edit:
# changes are overwritten. tuvl-generated
# ruff: noqa
# fmt: off

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, JsonValue


class ResearchBrief(BaseModel):
    """Model ResearchBrief (read)."""

    model_config = ConfigDict(extra="ignore")

    id: UUID | None = None
    question: str
    brief: str | None = None
    sources: JsonValue | None = None
    outcome: Literal["answered", "insufficient_sources", "capped"] | None = None
    tokens_used: int | None = None
    created_at: datetime | None = None


class ResearchInput(BaseModel):
    """Trigger input of workflow 'research'."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    question: str


class InvestigateIn(BaseModel):
    """Inputs of 'investigate' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    question: str


class InvestigateOut(BaseModel):
    """Outputs of 'investigate' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    research: JsonValue


class SummarizeSourceIn(BaseModel):
    """Inputs of 'summarize_source' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    url: str
    content: str


class SummarizeSourceOut(BaseModel):
    """Outputs of 'summarize_source' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    summary: JsonValue


class ComposeIn(BaseModel):
    """Inputs of 'compose' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    question: str
    research: JsonValue


class ComposeOut(BaseModel):
    """Outputs of 'compose' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    brief: str
    sources: list[JsonValue]


class PersistIn(BaseModel):
    """Inputs of 'persist' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    question: str
    brief: str
    sources: list[JsonValue]


class PersistOut(BaseModel):
    """Outputs of 'persist' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    saved: ResearchBrief


class PersistPartialIn(BaseModel):
    """Inputs of 'persist_partial' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    question: str


class PersistPartialOut(BaseModel):
    """Outputs of 'persist_partial' (research)."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    saved: ResearchBrief


ResearchEnd = Literal["default", "failed", "partial"]
InvestigateSignal = Literal["answered", "insufficient_sources"]
